import Head from 'next/head';
import {BsFileRichtextFill} from "react-icons/bs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joel Rivera | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-red-500 px-5'> 
<section className='bg-red-500 h-screen'>
  <nav className='py-10 mb-12 flex justify-between'>
    <h1 className='text-xl'>Hello</h1>
    <ul className='flex items-center'>
    <li><BsFileRichtextFill className='cursor-pointer'/>
    </li>
    <li><a className='bg-gradient-to-r from-red-700 to-red-300 rounded-sm px-2 py-1' href='#'>Resume</a></li>
    </ul>
  </nav>
  

</section>



      </main>

    </div>
  );
}
